
# #Selected targets

Selected_SimCRC_Targets_Both <- c(
  "Prev0AdOrPreClin_age27",#
  "Prev0AdOrPreClin_age32",
  "Prev0AdOrPreClin_age37",#new
  "Prev0AdOrPreClin_age42",#new
  "Prev0AdOrPreClin_age52",
  "Prev0AdOrPreClin_age62",
  "Prev0AdOrPreClin_age67",
  "Prev0AdOrPreClin_age77",
  "Prev1AdOrPreClin_age27",#new
  "Prev1AdOrPreClin_age32",#new
  "Prev1AdOrPreClin_age37",#new
  "Prev1AdOrPreClin_age42",#new
  "Prev1AdOrPreClin_age52",
  "Prev1AdOrPreClin_age62",
  "Prev1AdOrPreClin_age67",
  "Prev1AdOrPreClin_age77",
  "Prev2AdOrPreClin_age27",#new
  "Prev2AdOrPreClin_age32",#new
  "Prev2AdOrPreClin_age37",#new
  "Prev2AdOrPreClin_age42",
  "Prev2AdOrPreClin_age52",
  "Prev2AdOrPreClin_age62",
  "Prev2AdOrPreClin_age67",
  "Prev2AdOrPreClin_age77",
  "Prev3AdOrPreClin_age27",#new
  "Prev3AdOrPreClin_age32",#new
  "Prev3AdOrPreClin_age37",#new   
  "Prev3AdOrPreClin_age42",#new   
  "Prev3AdOrPreClin_age52",
  "Prev3AdOrPreClin_age62",
  "Prev3AdOrPreClin_age67",
  "Prev3AdOrPreClin_age77",
  "SizeLRGivenAdInP_wtd",
  "SizeMRGivenAdInP_wtd",
  "SizeHRGivenAdInP_wtd",
  "SizeLRGivenAdInD_wtd",
  "SizeMRGivenAdInD_wtd",
  "SizeHRGivenAdInD_wtd",
  "SizeLRGivenAdInR_wtd",
  "SizeMRGivenAdInR_wtd",
  "SizeHRGivenAdInR_wtd",
  "PrevPreclinical_ages50_59",
  "PrevPreclinical_ages60_69",
  "PrevPreclinical_ages70_79",
  "PrevPreclinical_ages80_89",
  "CRCincPer100K_P_ages50_59",
  "CRCincPer100K_P_ages60_69",
  "CRCincPer100K_P_ages70_79",
  "CRCincPer100K_P_ages80_99",
  "CRCincPer100K_D_ages50_59",
  "CRCincPer100K_D_ages60_69",
  "CRCincPer100K_D_ages70_79",
  "CRCincPer100K_D_ages80_99",
  "CRCincPer100K_R_ages50_59",
  "CRCincPer100K_R_ages60_69",
  "CRCincPer100K_R_ages70_79",
  "CRCincPer100K_R_ages80_99",
  "CRCincPer100K_ages50_59",
  "CRCincPer100K_ages60_69",
  "CRCincPer100K_ages70_79",
  "CRCincPer100K_ages80_99",
  "StageDistribution_P_S1",
  "StageDistribution_P_S2",
  "StageDistribution_P_S3",
  "StageDistribution_P_S4",
  "StageDistribution_D_S1",
  "StageDistribution_D_S2",
  "StageDistribution_D_S3",
  "StageDistribution_D_S4",
  "StageDistribution_R_S1",
  "StageDistribution_R_S2",
  "StageDistribution_R_S3",
  "StageDistribution_R_S4",
  "prop_SSP",
  "Prev0SSPOrPreClin_age32",
  "Prev0SSPOrPreClin_age37",
  "Prev0SSPOrPreClin_age42",
  "Prev0SSPOrPreClin_age47",
  "Prev0SSPOrPreClin_age52",
  "Prev0SSPOrPreClin_age57",
  "Prev0SSPOrPreClin_age62",
  "Prev0SSPOrPreClin_age67",
  "Prev0SSPOrPreClin_age72",
  "Prev0SSPOrPreClin_age77",
  "Prev1SSPOrPreClin_age32",
  "Prev1SSPOrPreClin_age37",
  "Prev1SSPOrPreClin_age42",
  "Prev1SSPOrPreClin_age47",
  "Prev1SSPOrPreClin_age52",
  "Prev1SSPOrPreClin_age57",
  "Prev1SSPOrPreClin_age62",
  "Prev1SSPOrPreClin_age67",
  "Prev1SSPOrPreClin_age72",
  "Prev1SSPOrPreClin_age77",
  "Prev2SSPOrPreClin_age32",
  "Prev2SSPOrPreClin_age37",
  "Prev2SSPOrPreClin_age42",
  "Prev2SSPOrPreClin_age47",
  "Prev2SSPOrPreClin_age52",
  "Prev2SSPOrPreClin_age57",
  "Prev2SSPOrPreClin_age62",
  "Prev2SSPOrPreClin_age67",
  "Prev2SSPOrPreClin_age72",
  "Prev2SSPOrPreClin_age77",
  "Prev3SSPOrPreClin_age32",
  "Prev3SSPOrPreClin_age37",
  "Prev3SSPOrPreClin_age42",
  "Prev3SSPOrPreClin_age47",
  "Prev3SSPOrPreClin_age52",
  "Prev3SSPOrPreClin_age57",
  "Prev3SSPOrPreClin_age62",
  "Prev3SSPOrPreClin_age67",
  "Prev3SSPOrPreClin_age72",
  "Prev3SSPOrPreClin_age77",
  "SizeLRGivenSSPInP_wtd",
  "SizeMRGivenSSPInP_wtd",
  "SizeHRGivenSSPInP_wtd",
  "SizeLRGivenSSPInD_wtd",
  "SizeMRGivenSSPInD_wtd",
  "SizeHRGivenSSPInD_wtd",
  "SizeLRGivenSSPInR_wtd",
  "SizeMRGivenSSPInR_wtd",
  "SizeHRGivenSSPInR_wtd" )

# #Selected targets
Selected_SimCRC_Targets_Adenoma <- c("Prev0AdOrPreClin_age27",
                                                     "Prev0AdOrPreClin_age32",
                                                     "Prev0AdOrPreClin_age37",
                                                     "Prev0AdOrPreClin_age42",
                                                     "Prev0AdOrPreClin_age47",
                                                     "Prev0AdOrPreClin_age52",
                                                     "Prev0AdOrPreClin_age57",
                                                     "Prev0AdOrPreClin_age62",
                                                     "Prev0AdOrPreClin_age67",
                                                     "Prev0AdOrPreClin_age72",
                                                     "Prev0AdOrPreClin_age77",
                                                     "Prev0AdOrPreClin_age82",
                                                     "Prev0AdOrPreClin_age87",
                                                     "Prev0AdOrPreClin_age92",
                                                     "Prev0AdOrPreClin_age97",
                                                     "Prev1AdOrPreClin_age27",   
                                                     "Prev1AdOrPreClin_age32",
                                                     "Prev1AdOrPreClin_age37",
                                                     "Prev1AdOrPreClin_age42",
                                                     "Prev1AdOrPreClin_age47",   
                                                     "Prev1AdOrPreClin_age52",
                                                     "Prev1AdOrPreClin_age57",
                                                     "Prev1AdOrPreClin_age62",
                                                     "Prev1AdOrPreClin_age67",   
                                                     "Prev1AdOrPreClin_age72",    
                                                     "Prev1AdOrPreClin_age77",   
                                                     "Prev1AdOrPreClin_age82",    
                                                     "Prev1AdOrPreClin_age87",   
                                                     "Prev1AdOrPreClin_age92",    
                                                     "Prev1AdOrPreClin_age97",    
                                                     "Prev2AdOrPreClin_age27",    
                                                     "Prev2AdOrPreClin_age32",   
                                                     "Prev2AdOrPreClin_age37",    
                                                     "Prev2AdOrPreClin_age42",    
                                                     "Prev2AdOrPreClin_age47",    
                                                     "Prev2AdOrPreClin_age52",   
                                                     "Prev2AdOrPreClin_age57",    
                                                     "Prev2AdOrPreClin_age62",    
                                                     "Prev2AdOrPreClin_age67",    
                                                     "Prev2AdOrPreClin_age72",   
                                                     "Prev2AdOrPreClin_age77",    
                                                     "Prev2AdOrPreClin_age82",
                                                     "Prev2AdOrPreClin_age87",
                                                     "Prev2AdOrPreClin_age92",
                                                     "Prev2AdOrPreClin_age97",
                                                     "Prev3AdOrPreClin_age27",    
                                                     "Prev3AdOrPreClin_age32",    
                                                     "Prev3AdOrPreClin_age37",   
                                                     "Prev3AdOrPreClin_age42",   
                                                     "Prev3AdOrPreClin_age47",   
                                                     "Prev3AdOrPreClin_age52",   
                                                     "Prev3AdOrPreClin_age57",   
                                                     "Prev3AdOrPreClin_age62",    
                                                     "Prev3AdOrPreClin_age67",    
                                                     "Prev3AdOrPreClin_age72",    
                                                     "Prev3AdOrPreClin_age77",   
                                                     "Prev3AdOrPreClin_age82",
                                                     "Prev3AdOrPreClin_age87",
                                                     "Prev3AdOrPreClin_age92",
                                                     "Prev3AdOrPreClin_age97",
                                                     "SizeLRGivenAdInP_wtd",         
                                                     "SizeMRGivenAdInP_wtd",         
                                                     "SizeHRGivenAdInP_wtd",         
                                                     "SizeLRGivenAdInD_wtd",         
                                                     "SizeMRGivenAdInD_wtd",         
                                                     "SizeHRGivenAdInD_wtd",         
                                                     "SizeLRGivenAdInR_wtd",         
                                                     "SizeMRGivenAdInR_wtd",         
                                                     "SizeHRGivenAdInR_wtd", 
                                                     "PrevPreclinical_ages40_49",
                                                     "PrevPreclinical_ages50_59",
                                                     "PrevPreclinical_ages60_69",
                                                     "PrevPreclinical_ages70_79",
                                                     "PrevPreclinical_ages80_89",
                                                     "CRCincPer100K_P_ages20_39", 
                                                     "CRCincPer100K_P_ages40_49", 
                                                     "CRCincPer100K_P_ages50_59", 
                                                     "CRCincPer100K_P_ages60_69",
                                                     "CRCincPer100K_P_ages70_79", 
                                                     "CRCincPer100K_P_ages80_99", 
                                                     "CRCincPer100K_D_ages20_39", 
                                                     "CRCincPer100K_D_ages40_49",
                                                     "CRCincPer100K_D_ages50_59", 
                                                     "CRCincPer100K_D_ages60_69", 
                                                     "CRCincPer100K_D_ages70_79", 
                                                     "CRCincPer100K_D_ages80_99",
                                                     "CRCincPer100K_R_ages20_39", 
                                                     "CRCincPer100K_R_ages40_49", 
                                                     "CRCincPer100K_R_ages50_59", 
                                                     "CRCincPer100K_R_ages60_69",
                                                     "CRCincPer100K_R_ages70_79", 
                                                     "CRCincPer100K_R_ages80_99", 
                                                     "CRCincPer100K_ages20_39",   
                                                     "CRCincPer100K_ages40_49",  
                                                     "CRCincPer100K_ages50_59",   
                                                     "CRCincPer100K_ages60_69",   
                                                     "CRCincPer100K_ages70_79",   
                                                     "CRCincPer100K_ages80_99",  
                                                     "StageDistribution_P_S1" ,   
                                                     "StageDistribution_P_S2" ,   
                                                     "StageDistribution_P_S3" ,   
                                                     "StageDistribution_P_S4" ,  
                                                     "StageDistribution_D_S1" ,   
                                                     "StageDistribution_D_S2" ,   
                                                     "StageDistribution_D_S3" ,   
                                                     "StageDistribution_D_S4" ,  
                                                     "StageDistribution_R_S1" ,   
                                                     "StageDistribution_R_S2" ,   
                                                     "StageDistribution_R_S3" ,   
                                                     "StageDistribution_R_S4" )


# #Selected targets
Selected_SimCRC_Targets_Mexico <- c(
  
  # Mexico Targets
  "PrevAnyAdOrPreClin_age45",
  "PrevAnyAdOrPreClin_age55",
  "PrevAnyAdOrPreClin_age65",
  "PrevAnyAdOrPreClin_age75",
  "PrevAnyAdOrPreClin_age85",
  "CRCincPer100K_ages20_24",
  "CRCincPer100K_ages25_29",
  "CRCincPer100K_ages30_34",
  "CRCincPer100K_ages35_39",
  "CRCincPer100K_ages40_44",
  "CRCincPer100K_ages45_49",
  "CRCincPer100K_ages50_54",
  "CRCincPer100K_ages55_59",
  "CRCincPer100K_ages60_64",
  "CRCincPer100K_ages65_69",
  "CRCincPer100K_ages70_74",
  "CRCincPer100K_ages75_79",
  "CRCincPer100K_ages80_84",
  "CRCincPer100K_ages85_89",
  "CRCincPer100K_ages90_94",
  "StageDistribution_S1",
  "StageDistribution_S2",
  "StageDistribution_S3",
  "StageDistribution_S4")


l_selectect_calibration_targets <- list(
  "Both" = Selected_SimCRC_Targets_Both,
  "Adenoma" = Selected_SimCRC_Targets_Adenoma,
  "Mexico" = Selected_SimCRC_Targets_Mexico
)


l_calibration_targets_files <- list(
  "Both_female" = "data-raw/20250626_simcrc_targets_ssp_unadjusted.csv",
  "Both_male"  = "data-raw/20250626_simcrc_targets_ssp_unadjusted.csv", 
  "Adenoma_female" = "data-raw/20220909_simcrc_targets_F.csv",
  "Adenoma_male" = "data-raw/20250904_simcrc_targets_M.csv",
  "Mexico" = "data-raw/20251016_simcrc_mx_targets.csv"
)

